110;9u104;9ugeneral {
	ignore_empty_input = true
}

animations {
	enabled = false
}

background {
	path = screenshot
	blur_passes = 3
	blue_size = 5
}

label {
	text = $USER

	color = rgba(255, 255, 255, 1.0)
	font_size = 16
	font_family = "JetBrainsMono Nerd Font Propo"

	position = 0, 50
}

input-field {
    size = 20%, 5%
    outline_thickness = 1
    inner_color = rgba(0, 0, 0, 0.5)

    outer_color = rgba(255, 255, 255, 1.0)
    check_color=rgba(255, 255, 255, 0.5)
    fail_color=rgba(245, 60, 60, 1.0)

	font_family="JetBrainsMono Nerd Font Propo"
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    rounding = 0

    position = 0, 0
    halign = center
    valign = center

    placeholder_text = password...
    check_text = checking...
    fail_text = incorrect
}
